### ISSUE TITLE
Am facing weird error 

### ISSUE THREAD

**Issue by antonadel05** [yashoswalyo/clone-bot-public#22]
Please help me with this
Process exited with status 1
2022-08-13T15:06:36.167961+00:00 app[worker.1]: Traceback (most recent call last):
2022-08-13T15:06:36.167982+00:00 app[worker.1]:   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2022-08-13T15:06:36.168090+00:00 app[worker.1]:     return _run_code(code, main_globals, None,
2022-08-13T15:06:36.168100+00:00 app[worker.1]:   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
2022-08-13T15:06:36.168177+00:00 app[worker.1]:     exec(code, run_globals)
2022-08-13T15:06:36.168185+00:00 app[worker.1]:   File "/usr/src/app/bot/__main__.py", line 35, in <module>
2022-08-13T15:06:36.168253+00:00 app[worker.1]:     from .helper.others.bot_utils import get_readable_file_size, get_readable_time
2022-08-13T15:06:36.168256+00:00 app[worker.1]:   File "/usr/src/app/bot/helper/others/bot_utils.py", line 11, in <module>
2022-08-13T15:06:36.168328+00:00 app[worker.1]:     from async_class import AsyncClass
2022-08-13T15:06:36.168340+00:00 app[worker.1]: ModuleNotFoundError: No module named 'async_class'
2022-08-13T15:06:36.691951+00:00 heroku[worker.1]: State changed from up to crashed

**Comment by yashoswalyo** [comment]
Why did you deploy **beta branch**?

**Comment by yashoswalyo** [comment]
I have used AsyncClass module, still it didn't work need to try some other way to update with interval
